#pragma once

#include "NativeGameplayTags.h"

// Movement tags
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Movement);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Movement_Jump);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Movement_Sprint);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Movement_Walk);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Movement_Crouch);

// Movement cooldown
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Cooldown_Movement_Sprint);

// Switch gun tags
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_SwitchGun);

// Switch cooldown
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Cooldown_SwitchGun);

// Gun Tags
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Gun_Aim);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Gun_Holster);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Gun_Reload);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Gun_Shoot);

// Ability tags
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Ability_Mobility_Dash);

// Passive tags
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Passive);

// Cues: Gun
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_GameplayCue_Gun_Bullet);

// Data
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Data_Damage);

// Cue: Damage
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_GameplayCue_Damage);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_GameplayCue_Damage_Gun);

// Events
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Event_Reload);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Event_Gun_Ready);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Event_Gun_Held);